# Following https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
---
language: python
python: "2.7"

addons:
  apt:
    packages:
      - python-pip
      - redis-tools

env:
  global:
    # Defaults
    test_host: localhost
    redis_password: passw0rd!
    redis_port: 6789

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible
  - pip install ansible

  # Install deps
  - ansible-galaxy install geerlingguy.pip geerlingguy.docker

script:
  # We'll add some commands to test the role here.
  # Check the role/playbook's syntax.
  - 'ansible-playbook -i tests/test_inv.yml tests/test_play.yml --syntax-check
     -e test_host=${test_host}'

  # Run the role/playbook with ansible-playbook.
  # add "-vvv" for complete output for debugging
  - 'ansible-playbook -i tests/test_inv.yml tests/test_play.yml --connection=local --sudo
     -e test_host=${test_host}'

#  # Run the role/playbook again, checking to make sure it's idempotent.
#  - >
#    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)

  - "redis-cli -p ${redis_port} -a '${redis_password}' info"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/