---
# tasks file for redis-server

- name: "Pull Redis image - redis:{{ redis_docker_image_tag }}"
  docker_image:
    name: 'redis'
    tag:  '{{ redis_docker_image_tag }}'

- name: "Setup Redis container on {{ redis_port }}:6379"
  docker_container:
    name: "{{ redis_container_name }}"
    image: "redis:{{ redis_docker_image_tag }}"
    command: ["redis-server", "--requirepass {{ redis_password }}"]
    state: started
    ports:
      - "{{ redis_port }}:6379"
    env:
      TZ: America/New_York
  register: redis_container

- name: Wait until Redis is available
  wait_for: port="{{ redis_port | int }}" delay=3
  when: redis_container.changed